enum RotationDirection {
    ROTATE_LEFT,
    ROTATE_RIGHT,
    ROTATE_STRAIGHT
};

enum Side {
    FRONT_SIDE,
    BACK_SIDE,
    LEFT_SIDE,
    RIGHT_SIDE,
    FRONT_LEFT_CORNER,
    FRONT_RIGHT_CORNER,
    BACK_LEFT_CORNER,
    BACK_RIGHT_CORNER
};

enum OpLabel {
    EVADE_FRONT,
    EVADE_BACK,
    EVADE_LEFT,
    EVADE_RIGHT,
    EVADE_FRONT_LEFT,
    EVADE_FRONT_RIGHT,
    EVADE_BACK_LEFT,
    EVADE_BACK_RIGHT
};
